const PLAYLIST_KEY="vip_playlist_state";
const DEVICE_KEY="vip_devices";
const SESSION_KEY="vip_device_session";
const ACCESS_KEY="vip_access_settings";
const GITHUB_PLAYLIST="https://raw.githubusercontent.com/mdmasumrana1580-design/AkashGo/refs/heads/main/ViP-Network.%20m3u";
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-ViP-Device-ID"};
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json;charset=utf-8",...C}});
const auth=(r,e)=>(!!e.ADMIN_PASSWORD&&(r.headers.get("Authorization")||"")===`Bearer ${e.ADMIN_PASSWORD}`);
const clean=u=>{u=String(u||"").trim();return /^hls:\/\//i.test(u)?"https://"+u.slice(6):u};
function cat(n,g=""){let t=(n+" "+g).toLowerCase();if(/sport|cricket|football|fifa|eurosport|willow|ten\s*cricket|ptv\s*sports|tsn|espn|bein|wwe|golf|nfl|nba/.test(t))return"Sports";if(/bangla|bangladesh|bd\b|somoy|jamuna|ekattor|dbc|maasranga|atn|channel\s*24|news24|independent|ntv|rtv|banglavision|boishakhi|gazi tv|gtv|b tv|duronto|deepto|nagorik|mohona|asian tv|desh tv|bijoy tv|mytv|satv|ekushey|bangla tv|btv/.test(t))return"BD";if(/india|indian|sony|zee|star|colors|set\b|sab\b|aaj tak|ndtv|republic|news18|times now|india tv|dd national|dd sports|sun tv|asianet|vijay|jaya|starplus|star gold|sony max|sony pix|sony wah|sony yay|sony pal|&pictures|b4u|movies now|mnx|hbo india/.test(t))return"India";return"Others"}
function parseM3U(t){let a=[],m=null;for(let raw of String(t||"").replace(/^\uFEFF/,"").replace(/\r/g,"").split("\n")){let l=raw.trim();if(!l)continue;if(/^#EXTINF/i.test(l)){let p=l.indexOf(","),left=p>=0?l.slice(0,p):l,right=p>=0?l.slice(p+1).trim():"Live Channel",gm=left.match(/group-title=["']([^"']*)["']/i),lm=left.match(/tvg-logo=["']([^"']*)["']/i),im=left.match(/tvg-id=["']([^"']*)["']/i),inline=right.match(/(?:https?|rtmp|rtsp|hls):\/\/\S+/i);m={name:(inline?right.slice(0,right.indexOf(inline[0])).trim():right)||"Live Channel",group:gm?gm[1]:"",logo:lm?lm[1]:"",tvgId:im?im[1]:""};if(inline){a.push({id:crypto.randomUUID(),name:m.name,group:m.group||cat(m.name),category:cat(m.name,m.group),logo:m.logo,url:clean(inline[0]),tvgId:m.tvgId,enabled:true,status:"unknown"});m=null}continue}if(l[0]==="#")continue;if(m){let u=clean(l);if(u)a.push({id:crypto.randomUUID(),name:m.name,group:m.group||cat(m.name),category:cat(m.name,m.group),logo:m.logo,url:u,tvgId:m.tvgId,enabled:true,status:"unknown"});m=null}else if(/^(https?|rtmp|rtsp|hls):\/\//i.test(l))a.push({id:crypto.randomUUID(),name:"Live Channel",group:"Others",category:"Others",logo:"",url:clean(l),tvgId:"",enabled:true,status:"unknown"})}return a}
function norm(a){return(Array.isArray(a)?a:[]).filter(c=>c&&c.url).map((c,i)=>({id:c.id||crypto.randomUUID(),name:String(c.name||c.title||`Channel ${i+1}`).trim(),group:String(c.group||c.category||"Others").trim()||"Others",category:["Sports","BD","India","Others"].includes(c.category)?c.category:cat(c.name,c.group),logo:String(c.logo||"").trim(),url:clean(c.url),tvgId:String(c.tvgId||"").trim(),enabled:c.enabled!==false,status:c.status||"unknown",http:c.http||0,checkedAt:c.checkedAt||null}))}
async function state(e){let s=await e.PLAYLIST_KV.get(PLAYLIST_KEY);if(s)try{return JSON.parse(s)}catch{}return{version:1,updatedAt:new Date().toISOString(),notice:"",headline:"",channels:[]}}
async function save(e,s){s.channels=norm(s.channels);s.version=1;s.updatedAt=new Date().toISOString();await e.PLAYLIST_KV.put(PLAYLIST_KEY,JSON.stringify(s));return s}
function m3u(s){return"#EXTM3U\n"+(s.channels||[]).filter(c=>c.enabled!==false).map(c=>`#EXTINF:-1 tvg-id="${c.tvgId||""}" tvg-logo="${c.logo||""}" group-title="${c.group||c.category}",${c.name}\n${clean(c.url)}`).join("\n")+"\n"}
async function check(u){u=clean(u);if(!u)return{ok:false,status:"unknown",http:0};let ac=new AbortController(),tm=setTimeout(()=>ac.abort(),8000);try{let r=await fetch(u,{redirect:"follow",signal:ac.signal,headers:{"User-Agent":"ViP-tv-Checker/1.0","Accept":"*/*"}});return{ok:r.status>=200&&r.status<400,status:r.status>=200&&r.status<400?"active":"dead",http:r.status,contentType:r.headers.get("content-type")||""}}catch(x){return{ok:false,status:"dead",http:0,error:x.message}}finally{clearTimeout(tm)}}
async function xt(server,user,pass){server=String(server||"").trim().replace(/\/+$/," ").trim().replace(/\/player_api\.php.*$/i,"");if(!server||!user||!pass)throw Error("Xtream server, username and password required");let base=server+"/player_api.php?username="+encodeURIComponent(user)+"&password="+encodeURIComponent(pass),r=await fetch(base);if(!r.ok)throw Error("Xtream HTTP "+r.status);let info=await r.json(),sr=await fetch(base+"&action=get_live_streams");if(!sr.ok)throw Error("Xtream streams HTTP "+sr.status);let arr=await sr.json();if(!Array.isArray(arr))throw Error("No live streams");return{channels:arr.map((x,i)=>({id:crypto.randomUUID(),name:x.name||`Xtream Channel ${i+1}`,group:x.category_name||"Others",category:cat(x.name,x.category_name),logo:x.stream_icon||"",url:`${server}/live/${encodeURIComponent(user)}/${encodeURIComponent(pass)}/${x.stream_id}.${x.container_extension||"ts"}`,tvgId:x.epg_channel_id||"",enabled:true,status:"unknown"})),userInfo:info.user_info||{}}}
async function sessionVersion(e){return await e.PLAYLIST_KV.get(SESSION_KEY)||"1"}
async function bumpSession(e){let x=String(Number(await sessionVersion(e))+1);await e.PLAYLIST_KV.put(SESSION_KEY,x);return x}
async function devices(e){let x=await e.PLAYLIST_KV.get(DEVICE_KEY);if(x)try{return JSON.parse(x)}catch{}return[]}
async function saveDevices(e,a){await e.PLAYLIST_KV.put(DEVICE_KEY,JSON.stringify(a));return a}
async function accessSettings(e){let x=await e.PLAYLIST_KV.get(ACCESS_KEY);if(x)try{let s=JSON.parse(x);return{accessEnabled:s.accessEnabled!==false,requireApproval:s.requireApproval===true,updatedAt:s.updatedAt||null}}catch{}return{accessEnabled:true,requireApproval:false,updatedAt:null}}
async function saveAccessSettings(e,b){let s={accessEnabled:b.accessEnabled!==false,requireApproval:b.requireApproval===true,updatedAt:new Date().toISOString()};await e.PLAYLIST_KV.put(ACCESS_KEY,JSON.stringify(s));return s}
function deviceIdFrom(r,b){return String(b?.deviceId||r.headers.get("X-ViP-Device-ID")||"").trim().slice(0,120)}
function deviceInfo(r,b){return{deviceId:deviceIdFrom(r,b),name:String(b?.name||"Android Device").slice(0,120),model:String(b?.model||"").slice(0,120),platform:String(b?.platform||"").slice(0,80),app:String(b?.app||"ViP-tv").slice(0,50),ip:"",lastSeen:new Date().toISOString()}}
async function deviceRegister(r,e,b){let id=deviceIdFrom(r,b);if(!id)return J({ok:false,allowed:false,reason:"device-id-required"},400);let settings=await accessSettings(e),a=await devices(e),d=a.find(x=>x.deviceId===id),isNew=!d;
if(!d){d=deviceInfo(r,b);d.blocked=false;d.approved=!settings.requireApproval;d.createdAt=d.lastSeen;d.sessionVersion=await sessionVersion(e);a.push(d)}else{d.lastSeen=new Date().toISOString();Object.assign(d,{name:String(b?.name||d.name||"").slice(0,120),model:String(b?.model||d.model||"").slice(0,120),platform:String(b?.platform||d.platform||"").slice(0,80),app:String(b?.app||d.app||"").slice(0,50)})}
let sv=await sessionVersion(e);if(d.sessionVersion!==sv||d.sessionRevoked===true){
  if(settings.accessEnabled && !d.blocked && d.approved && !settings.requireApproval){
    d.sessionVersion=sv;d.sessionRevoked=false;d.lastSeen=new Date().toISOString();await saveDevices(e,a);
  }else{
    d.sessionRevoked=true;await saveDevices(e,a);return J({ok:true,allowed:false,pending:false,reason:"session-revoked",settings,device:d,sessionVersion:sv})
  }
}
if(!settings.accessEnabled){return J({ok:true,allowed:false,pending:false,reason:"access-disabled",settings,device:d,sessionVersion:sv})}
if(d.blocked===true){await saveDevices(e,a);return J({ok:true,allowed:false,pending:false,reason:"blocked",settings,device:d,sessionVersion:sv})}
if(settings.requireApproval&&!d.approved){await saveDevices(e,a);return J({ok:true,allowed:false,pending:true,reason:"approval-required",settings,device:d,sessionVersion:sv})}
d.approved=true;d.sessionRevoked=false;await saveDevices(e,a);return J({ok:true,allowed:true,pending:false,reason:"ok",isNew,settings,device:d,sessionVersion:sv})}
async function deviceCheck(r,e){let id=deviceIdFrom(r,null),settings=await accessSettings(e);if(!id)return J({ok:true,allowed:false,reason:"device-id-required",settings},400);let sv=await sessionVersion(e),d=(await devices(e)).find(x=>x.deviceId===id);if(!settings.accessEnabled)return J({ok:true,allowed:false,reason:"access-disabled",settings,device:d||null,sessionVersion:sv});if(!d)return J({ok:true,allowed:false,pending:settings.requireApproval,reason:"device-not-registered",settings,device:null,sessionVersion:sv});if(d.sessionVersion!==sv||d.sessionRevoked===true)return J({ok:true,allowed:false,reason:"session-revoked",settings,device:d,sessionVersion:sv});if(d.blocked)return J({ok:true,allowed:false,reason:"blocked",settings,device:d,sessionVersion:sv});if(settings.requireApproval&&!d.approved)return J({ok:true,allowed:false,pending:true,reason:"approval-required",settings,device:d,sessionVersion:sv});return J({ok:true,allowed:true,reason:"ok",settings,device:d,sessionVersion:sv})}
export default{async fetch(r,e){let u=new URL(r.url);if(r.method==="OPTIONS")return new Response(null,{status:204,headers:C});try{
if(u.pathname==="/"&&r.method==="GET")return new Response("ViP-tv Worker is running.",{headers:C});
if(u.pathname==="/api/state"&&r.method==="GET")return J(await state(e));
if(u.pathname==="/api/playlist"&&r.method==="GET")return new Response(m3u(await state(e)),{headers:{"Content-Type":"audio/x-mpegurl;charset=utf-8",...C}});
if(u.pathname==="/api/admin/ping"&&r.method==="GET"){if(!auth(r,e))return J({error:"Unauthorized"},401);return J({ok:true})}
if(u.pathname==="/api/admin/state"&&r.method==="GET"){if(!auth(r,e))return J({error:"Unauthorized"},401);return J(await state(e))}
if((u.pathname==="/api/admin/state"||u.pathname==="/api/state")&&r.method==="PUT"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),s=await state(e);return J({ok:true,state:await save(e,{...s,...b,channels:b.channels??s.channels})})}
if(u.pathname==="/api/admin/playlist"&&r.method==="GET"){if(!auth(r,e))return J({error:"Unauthorized"},401);let s=await state(e);return J({ok:true,playlist:m3u(s),channels:s.channels})}
if(u.pathname==="/api/admin/playlist"&&r.method==="PUT"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),s=await state(e);s.channels=parseM3U(b.playlist||"");if(!s.channels.length)return J({error:"No valid channels found"},400);return J({ok:true,imported:s.channels.length,state:await save(e,s)})}
if((u.pathname==="/api/admin/import-m3u"||u.pathname==="/api/admin/import-m3u-url")&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),txt=b.playlist;if(!txt){let rr=await fetch(String(b.url||"").trim());if(!rr.ok)return J({error:"M3U HTTP "+rr.status},400);txt=await rr.text()}let ch=parseM3U(txt);if(!ch.length)return J({error:"No valid channels found"},400);let s=await state(e);s.channels=ch;return J({ok:true,imported:ch.length,state:await save(e,s)})}
if(u.pathname==="/api/admin/refresh-github"&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let rr=await fetch(GITHUB_PLAYLIST);if(!rr.ok)return J({error:"GitHub HTTP "+rr.status},400);let ch=parseM3U(await rr.text());if(!ch.length)return J({error:"No valid channels found"},400);let s=await state(e);s.channels=ch;return J({ok:true,imported:ch.length,state:await save(e,s)})}
if(u.pathname==="/api/check"&&r.method==="GET"){if(!auth(r,e))return J({error:"Unauthorized"},401);return J(await check(u.searchParams.get("url")||""))}
if(u.pathname==="/api/admin/check-all"&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let s=await state(e),a=s.channels||[],res=[];for(let i=0;i<a.length;i+=8){let b=a.slice(i,i+8),z=await Promise.all(b.map(async c=>({id:c.id,name:c.name,...await check(c.url)})));z.forEach(x=>{let c=a.find(q=>q.id===x.id);if(c){c.status=x.status;c.http=x.http||0;c.checkedAt=new Date().toISOString()}});res.push(...z)}await save(e,s);return J({ok:true,total:a.length,active:a.filter(c=>c.status==="active").length,dead:a.filter(c=>c.status==="dead").length,unknown:a.filter(c=>c.status==="unknown").length,results:res})}
if(u.pathname==="/api/xtream/import"&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),x=await xt(b.server,b.username,b.password),s=await state(e);s.channels=x.channels;await save(e,s);return J({ok:true,imported:x.channels.length,channels:x.channels,userInfo:x.userInfo})}
if(u.pathname==="/api/device/register"&&r.method==="POST"){let b=await r.json().catch(()=>({}));return deviceRegister(r,e,b)}
if(u.pathname==="/api/device/check"&&r.method==="GET")return deviceCheck(r,e);
if(u.pathname==="/api/admin/settings"&&r.method==="GET"){if(!auth(r,e))return J({error:"Unauthorized"},401);return J({ok:true,settings:await accessSettings(e)})}
if(u.pathname==="/api/admin/settings"&&r.method==="PUT"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),s=await saveAccessSettings(e,b||{});return J({ok:true,settings:s})}
if(u.pathname==="/api/admin/devices/logout-all"&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let sv=await bumpSession(e);return J({ok:true,sessionVersion:sv,message:"All devices logged out"})}
if(u.pathname==="/api/admin/devices/approve"&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),a=await devices(e),d=a.find(x=>x.deviceId===String(b.deviceId||""));if(!d)return J({error:"Device not found"},404);d.approved=true;d.blocked=false;d.sessionRevoked=false;d.sessionVersion=await sessionVersion(e);await saveDevices(e,a);return J({ok:true,device:d})}
if(u.pathname==="/api/admin/devices/approve-all"&&r.method==="POST"){if(!auth(r,e))return J({error:"Unauthorized"},401);let a=await devices(e),sv=await sessionVersion(e),n=0;a.forEach(d=>{if(!d.blocked&&!d.approved){d.approved=true;d.sessionRevoked=false;d.sessionVersion=sv;n++}});await saveDevices(e,a);return J({ok:true,approved:n,devices:a})}
if(u.pathname==="/api/admin/devices"&&r.method==="GET"){if(!auth(r,e))return J({error:"Unauthorized"},401);return J({ok:true,devices:await devices(e),settings:await accessSettings(e)})}
if(u.pathname==="/api/admin/devices"&&r.method==="PUT"){if(!auth(r,e))return J({error:"Unauthorized"},401);let b=await r.json(),a=await devices(e),id=String(b.deviceId||""),d=a.find(x=>x.deviceId===id);if(!d)return J({error:"Device not found"},404);if(typeof b.blocked==="boolean")d.blocked=b.blocked;if(typeof b.approved==="boolean")d.approved=b.approved;if(b.name!==undefined)d.name=String(b.name).slice(0,120);await saveDevices(e,a);return J({ok:true,device:d})}
if(u.pathname==="/api/admin/devices"&&r.method==="DELETE"){if(!auth(r,e))return J({error:"Unauthorized"},401);let id=u.searchParams.get("deviceId")||"",a=await devices(e),n=a.filter(x=>x.deviceId!==id);if(n.length===a.length)return J({error:"Device not found"},404);await saveDevices(e,n);return J({ok:true})}return new Response("ViP-tv Worker is running.",{headers:C})
}catch(x){return J({ok:false,error:x.message||"Server error"},500)}}};
if(e.ASSETS && typeof e.ASSETS.fetch==="function")
return e.ASSETS.fetch(r);
