name = "vip-network-tv"
main = "worker.js"
compatibility_date = "2026-09-05"

[assets]
directory = "./site"
binding = "ASSETS"

[[kv_namespaces]]
binding = "VIP_PLAYLIST"
id = "a5a1d0c299654c43a02cc4def3973e27"
